config/routes.rb
Rails.application.routes.draw do


  get 'evaluate/evaluation', to: 'evaluate#evaluation'

  get 'apply/studyleave', to: 'apply#studyleave'

  get 'apply/dsf', to: 'apply#dsf'

  get 'apply/sabbatical', to: 'apply#sabbatical'

  get 'apply/specialdetail', to: 'apply#specialdetail'

  get 'apply/enrollmentprivileges', to: 'apply#enrollmentprivileges'

  get 'web_pages/rsocalculator', to: 'web_pages#rsocalculator'

  root 'web_pages#landingpage'

  get '/landingpage', to: 'web_pages#landingpage'

  get '/rsocalculator', to: 'web_pages#rsocalculator'

  get 'contacts/contactus',   to: 'contacts#new'

  get 'contacts/create',    to: 'contacts#create'


  get 'evaluate/evaluation', to: 'evaluate#eval_SL'

  get 'evaluate/evaluation', to: 'evaluate#eval_DSF'

  get 'evaluate/evaluation', to: 'evaluate#eval_Sab'

  get 'evaluate/evaluation', to: 'evaluate#eval_SD'

  get 'evaluate/evaluation', to: 'evaluate#eval_EP'

  resources :apply
  resources :evaluate
  resources :contacts, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="ui red center aligned inverted vertical footer segment">
  <div class="ui horizontal inverted small divided link list">
    <%= link_to "Osmeña Avenue, Diliman,  Quezon City,  Metro Manila", "https://www.google.com.ph/maps/place/Quezon+Hall/@14.6548946,121.0650716,15z/data=!4m5!3m4!1s0x0:0x78351c9414d84f
    d6!8m2!3d14.6548946!4d121.0650716", class: "item" %>


    <%= link_to "hrdo.updiliman@up.edu.ph", contact_contactus_path, class: "item" %>


    <%= link_to "uphrdotraining@gmail.com", "https://uphrdotna.herokuapp.com", class: "item" %><a> </a>
    <%= link_to "hrdo.upd.edu.ph", "http://hrdo.upd.edu.ph/", class: "item" %>
    <p><br>Copyright © 2017<p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="ui red fixed inverted stackable menu">
  <div class="ui container" id="hybrid">
    <%= link_to  image_tag("logo_white.png") + "HRDO Scholarship and Fellowship Services".html_safe, landingpage_path, class: "item" %>

    <%= link_to "Self Evaluation", evaluate_evaluation_path, class: "item" %>

    <div class="ui inactive simple dropdown item">
      <a href="">Application Process</a><i class="dropdown icon"></i>
      <div class="menu">
        <%= link_to "Study Leave", apply_studyleave_path, class: "item" %>
        <%= link_to "Doctoral Studies Fund", apply_dsf_path , class: "item" %>
        <%= link_to "Sabbatical", apply_sabbatical_path, class: "item" %>
        <%= link_to "Special Detail", apply_specialdetail_path, class: "item" %>
        <%= link_to "Enrollment Privileges", apply_enrollmentprivileges_path, class: "item" %>
      </div>
    </div>
    <%= link_to "RSO Calculator", rsocalculator_path, class: "item"%>

    <%= link_to "Contact Us", contacts_contactus_path, class: "item"%>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>HRDOSAFS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">


  </head>
  <%= render 'layouts/header' %>
  <body>
    <%= yield %>
    <%= render 'layouts/footer' %>

  </body>


</html>